@endpoint=http://localhost:3000

### création d'une task
POST {{endpoint}}/tasks
Content-Type: application/json

{
    "name": "Le nom de ma nouvelle tâche"
}

### patch task
PATCH {{endpoint}}/tasks/1
Content-Type: application/json

{
    "name": "dfgbfg"
}